name: Broken Links Check

on:
  workflow_dispatch:
  schedule:
    # Every week on Sunday
    - cron: "0 0 * * 0"

jobs:
  broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Check Broken Links
        run: npx links-awakening 'https://joshghent.com'
