# Grabs the image JSON from iCloud and commit the update
name: "Photos"
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  photos-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: bahmutov/npm-install@v1

      - name: Process Data
        run: node ./photos.js
        env:
          ICLOUD_ALBUM_ID: ${{ secrets.ICLOUD_ALBUM_ID }}

      - name: Commit and push
        run: |
          git config --global init.defaultBranch master
          git config --global user.email "bot@joshghent.com"
          git config --global user.name "photos [bot]"
          git add .
          git commit -m "📸 Update photos" || echo "Nothing to commit"
          git push origin HEAD:master
