name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "add,Adds,new"
          major-wording: "MAJOR,cut-major,feat,fix"
          patch-wording: "patch,fixes,chore,bump"
          rc-wording: "RELEASE,alpha"
