name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v3
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        minor-wording:  'add,Adds,new'
        major-wording:  'MAJOR,cut-major,feat,fix'
        patch-wording:  'patch,fixes,chore,bump'     # Providing patch-wording will override commits
                                          # defaulting to a patch bump.
        rc-wording:     'RELEASE,alpha'
