name: Test

on:
  push:
    branches:
      - "**"
      - "!master"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      site_url: ${{ steps.cloudflare_preview_url.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install
        run: npm ci --no-audit

      - run: sleep 30
      - name: cloudflare-preview-url
        uses: zentered/cloudflare-preview-url@v1.4.0
        id: cloudflare_preview_url
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          cloudflare_project_id: "joshghent"
          wait_until_ready: true
      - name: Get URL
        run: echo "https://${{ steps.cloudflare_preview_url.outputs.preview_url }}"
  carbon:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Calculate CO2 🌱
        uses: GeopJr/CO2@v1
        with:
          url: ${{ needs.setup.outputs.site_url }}
          renewable: true
          comment: true
          token: ${{github.token}}

  lighthouse:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: ${{ needs.setup.outputs.site_url }}
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
